# Generated by Django 3.2.1 on 2021-05-06 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='images',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.discounts', verbose_name='Акция'),
        ),
        migrations.AddField(
            model_name='discounts',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='discounts',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.partner', verbose_name='Партнер'),
        ),
    ]
