# Generated by Django 3.2.1 on 2021-05-07 12:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20210506_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherPhones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Другие номера',
                'verbose_name_plural': 'Другие номера',
            },
        ),
        migrations.CreateModel(
            name='Felials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(blank=True, max_length=255, verbose_name='Адресс')),
            ],
            options={
                'verbose_name': 'Фелиалы',
                'verbose_name_plural': 'Фелиалы',
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='active',
            field=models.BooleanField(blank=True, default=False, verbose_name='Прошел проверку модератором/администратором'),
        ),
        migrations.AddField(
            model_name='partner',
            name='adress',
            field=models.CharField(default=' ', max_length=255, verbose_name='Адресс'),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_face',
            field=models.CharField(default=' ', max_length=255, verbose_name='контактное лицо'),
        ),
        migrations.AddField(
            model_name='partner',
            name='date_of_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 7, 17, 48, 7, 844415), verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='partner',
            name='email',
            field=models.CharField(default=' ', max_length=255, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='partner',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка на facebook'),
        ),
        migrations.AddField(
            model_name='partner',
            name='inn',
            field=models.PositiveIntegerField(default=0, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='partner',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка на instagram'),
        ),
        migrations.AddField(
            model_name='partner',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка на linkedin'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='date_of_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 7, 17, 48, 7, 845415), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='date_of_finish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 7, 17, 48, 7, 845415), verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='images',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainApp.discounts', verbose_name='Акция'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.CharField(default=' ', max_length=255, verbose_name='Телефон (основной)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='mainApp.discounts', verbose_name='Акция'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product',
            field=models.CharField(blank=True, max_length=255, verbose_name='Объект акции/скидки'),
        ),
        migrations.DeleteModel(
            name='Requests',
        ),
        migrations.AddField(
            model_name='felials',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='felials', to='mainApp.partner', verbose_name='Партнер'),
        ),
        migrations.AddField(
            model_name='anotherphones',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='another_phones', to='mainApp.partner', verbose_name='Партнер'),
        ),
    ]
