# Generated by Django 3.2.1 on 2021-05-07 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20210507_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_az',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Название (az)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Название (en)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tj',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Название (tj)'),
        ),
        migrations.AddField(
            model_name='discounts',
            name='body_az',
            field=models.TextField(blank=True, verbose_name='Описание (az)'),
        ),
        migrations.AddField(
            model_name='discounts',
            name='body_en',
            field=models.TextField(blank=True, verbose_name='Описание (en)'),
        ),
        migrations.AddField(
            model_name='discounts',
            name='body_tj',
            field=models.TextField(blank=True, verbose_name='Описание (tj)'),
        ),
        migrations.AddField(
            model_name='felials',
            name='adress_az',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адресс (az)'),
        ),
        migrations.AddField(
            model_name='felials',
            name='adress_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адресс (en)'),
        ),
        migrations.AddField(
            model_name='felials',
            name='adress_tj',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адресс (tj)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='adress_az',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адресс (az)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='adress_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адресс (en)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='adress_tj',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адресс (tj)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_az',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (az)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (en)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_tj',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (tj)'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_az',
            field=models.CharField(blank=True, max_length=255, verbose_name='Объект акции/скидки (az)'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Объект акции/скидки (en)'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_tj',
            field=models.CharField(blank=True, max_length=255, verbose_name='Объект акции/скидки (tj)'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='date_of_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 7, 18, 3, 41, 117510), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='date_of_finish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 7, 18, 3, 41, 117510), verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='date_of_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 7, 18, 3, 41, 116511), verbose_name='Дата создания'),
        ),
    ]
