# Generated by Django 3.2.1 on 2021-05-07 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20210507_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='discounts',
            name='body_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='discounts',
            name='body_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='discounts',
            name='name_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='discounts',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='discounts',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='discounts',
            name='name_tj',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='discounts',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='felials',
            name='adress_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адресс'),
        ),
        migrations.AddField(
            model_name='felials',
            name='adress_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адресс'),
        ),
        migrations.AddField(
            model_name='partner',
            name='adress_ru',
            field=models.CharField(default=' ', max_length=255, null=True, verbose_name='Адресс'),
        ),
        migrations.AddField(
            model_name='partner',
            name='adress_uz',
            field=models.CharField(default=' ', max_length=255, null=True, verbose_name='Адресс'),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_face_az',
            field=models.CharField(default=' ', max_length=255, null=True, verbose_name='контактное лицо'),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_face_en',
            field=models.CharField(default=' ', max_length=255, null=True, verbose_name='контактное лицо'),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_face_ru',
            field=models.CharField(default=' ', max_length=255, null=True, verbose_name='контактное лицо'),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_face_tj',
            field=models.CharField(default=' ', max_length=255, null=True, verbose_name='контактное лицо'),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_face_uz',
            field=models.CharField(default=' ', max_length=255, null=True, verbose_name='контактное лицо'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Объект акции/скидки'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Объект акции/скидки'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_az',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_tj',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='body_az',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='body_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='body_tj',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='date_of_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 8, 1, 24, 11, 585892), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='date_of_finish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 8, 1, 24, 11, 585892), verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='felials',
            name='adress_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='felials',
            name='adress_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='felials',
            name='adress_tj',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='adress_az',
            field=models.CharField(default=' ', max_length=255, null=True, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='adress_en',
            field=models.CharField(default=' ', max_length=255, null=True, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='adress_tj',
            field=models.CharField(default=' ', max_length=255, null=True, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='date_of_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 8, 1, 24, 11, 585892), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name_tj',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Объект акции/скидки'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Объект акции/скидки'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_tj',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Объект акции/скидки'),
        ),
    ]
