# Generated by Django 3.2.1 on 2021-05-07 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_auto_20210508_0142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_tj',
            new_name='name_tg_TJ',
        ),
        migrations.RenameField(
            model_name='discounts',
            old_name='body_tj',
            new_name='body_tg_TJ',
        ),
        migrations.RenameField(
            model_name='discounts',
            old_name='name_tj',
            new_name='name_tg_TJ',
        ),
        migrations.RenameField(
            model_name='felials',
            old_name='adress_tj',
            new_name='adress_tg_TJ',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='adress_tj',
            new_name='adress_tg_TJ',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='contact_face_tj',
            new_name='contact_face_tg_TJ',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='name_tj',
            new_name='name_tg_TJ',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_tj',
            new_name='product_tg_TJ',
        ),
        migrations.AlterField(
            model_name='discounts',
            name='date_of_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 8, 3, 18, 24, 494165), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='date_of_finish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 8, 3, 18, 24, 494165), verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='date_of_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 8, 3, 18, 24, 493166), verbose_name='Дата создания'),
        ),
    ]
