# Generated by Django 3.2.1 on 2021-05-07 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_auto_20210508_0318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_tg_TJ',
            new_name='name_tg',
        ),
        migrations.RenameField(
            model_name='discounts',
            old_name='body_tg_TJ',
            new_name='body_tg',
        ),
        migrations.RenameField(
            model_name='discounts',
            old_name='name_tg_TJ',
            new_name='name_tg',
        ),
        migrations.RenameField(
            model_name='felials',
            old_name='adress_tg_TJ',
            new_name='adress_tg',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='adress_tg_TJ',
            new_name='adress_tg',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='contact_face_tg_TJ',
            new_name='contact_face_tg',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='name_tg_TJ',
            new_name='name_tg',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_tg_TJ',
            new_name='product_tg',
        ),
        migrations.AlterField(
            model_name='discounts',
            name='date_of_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 8, 3, 19, 49, 915943), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='date_of_finish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 8, 3, 19, 49, 915943), verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='date_of_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 8, 3, 19, 49, 915943), verbose_name='Дата создания'),
        ),
    ]
