# Generated by Django 3.2.1 on 2021-05-16 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_auto_20210516_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='rating_used',
            field=models.BooleanField(default=False, verbose_name='Поставил оценку'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='date_of_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 16, 22, 51, 9, 632327), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='date_of_finish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 16, 22, 51, 9, 632327), verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='date_of_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 16, 22, 51, 9, 631314), verbose_name='Дата создания'),
        ),
    ]
