# Generated by Django 3.2.1 on 2021-05-06 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_register',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 6, 17, 45, 12, 648935), null=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 6, 17, 45, 12, 648935), verbose_name='Последняя активность'),
        ),
    ]
