# Generated by Django 3.2.1 on 2021-05-07 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0005_auto_20210506_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='client',
            field=models.BooleanField(default=True, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_register',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 7, 17, 48, 7, 842425), null=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 7, 17, 48, 7, 842425), verbose_name='Последняя активность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner',
            field=models.BooleanField(default=False, verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribe',
            field=models.BooleanField(default=False, verbose_name='Подписка'),
        ),
    ]
