# Generated by Django 3.2.1 on 2021-05-07 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0006_auto_20210507_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_register',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 7, 18, 3, 41, 114510), null=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 7, 18, 3, 41, 114510), verbose_name='Последняя активность'),
        ),
    ]
