# Generated by Django 3.2.1 on 2021-05-07 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0010_auto_20210508_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_register',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 8, 3, 19, 49, 915943), null=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 8, 3, 19, 49, 915943), verbose_name='Последняя активность'),
        ),
    ]
