# Generated by Django 3.2.1 on 2021-05-09 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0011_auto_20210508_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_register',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 9, 21, 16, 7, 29403), null=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 9, 21, 16, 7, 29403), verbose_name='Последняя активность'),
        ),
    ]
